server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.192.1:8761/eureka/

spring:
  application:
    name: gateway-service

  config:
    import: optional:configserver:http://192.168.192.1:8888

