apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  labels:
    app: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      initContainers:
        - name: wait-for-config
          image: curlimages/curl:8.7.1
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              echo "Waiting for config-service...";
              until curl -s http://config-service:8888/actuator/health | grep '"status":"UP"' > /dev/null; do
                echo "Config-service not ready yet. Waiting...";
                sleep 3;
              done
              echo "Config-service is UP.";

#        - name: wait-for-discovery
#          image: curlimages/curl:8.7.1
#          command: [ "/bin/sh", "-c" ]
#          args:
#            - |
#              echo "Waiting for discovery-service...";
#              until curl -s http://discovery-service:8761/actuator/health | grep '"status":"UP"' > /dev/null; do
#                echo "Discovery-service not ready yet. Waiting...";
#                sleep 3;
#              done
#              echo "Discovery-service is UP.";

      containers:
        - name: gateway-service
          image: lhdmir/gateway-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: CONFIG_SERVER_URL
              value: http://config-service:8888
#            - name: EUREKA_URL
#              value: http://discovery-service:8761/eureka
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5