name: Deploy Gateway Service (on PR merge to main)

on:
  pull_request:
    types: [closed]
    branches: [ main ]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: [self-hosted, gateway-service]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant Gradle wrapper permission
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USER }}/gateway-service:latest .

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
          docker push ${{ secrets.DOCKER_USER }}/gateway-service:latest

      - name: Copy Kubernetes manifest to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "./k8s/gateway-service.yml"
          target: "~/gateway/"

      - name: Deploy to Kubernetes on remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/gateway/k8s
            kubectl delete deployment gateway-service --ignore-not-found
            kubectl apply -f gateway-service.yml